language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm run test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT	  
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
