language: node_js
node_js:
  - 10.15.3
cache:
  directories:
  - node_modules
addons:
  code_climate
git:
  depth: 
    - 50
  quiet: 
    - true

before_script:
  - export CC_TEST_REPORTER_ID=af25a20f2a1169b8d9c86e0d67b663af715c162718e519d6fd468dc9c66b8552
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
Collapse 

