export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const CREATE_PARCEL_SUCCESS = "CREATE_PARCEL_SUCCESS"
export const CREATE_PARCEL_FAIL = "CREATE_PARCEL_FAIL"
export const GET_PARCEL_FAIL = "GET_PARCEL_FAIL"
export const GET_PARCEL_SUCCESS = "GET_PARCEL_SUCCESS"
